default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password: 031.053.
    #host: videos_db
    #socket: /tmp/mysql.sock
development:
    <<: *default
    database: videos
